### ISSUE TITLE
playlist_manager issues (SSL & config usage)

### ISSUE THREAD

**Issue by camjac251** [blacktwin/JBOPS#106]
Is playlist manager ready for main use?

I am trying to get it working but face an SSL error with Tautulli since I have my wildcard SSL certificate attached to that for domain usage as well as it not loading the config info, while killstreams does.

I get this error if I don't fill in any info in the script itself
```bash
Traceback (most recent call last):
  File "playlist_manager.py", line 91, in <module>
    PLEX_URL = CONFIG.data['auth'].get('server_baseurl')
KeyError: 'auth'
```
and if I do, I get an SSL error with hostnames.

```bash
python3 playlist_manager.py --jbop mostPopularTv --action show
Tautulli API 'get_home_stats' request failed: HTTPSConnectionPool(host='127.0.0.1', port=12345): Max retries exceeded with url: /api/v2?apikey=***************&cmd=get_home_stats&time_range=30&stats_count=5&stats_type=0 (Caused by SSLError(CertificateError("hostname '127.0.0.1' doesn't match either of '*.domain.com', 'domain.com'",),)).Traceback (most recent call last):
  File "playlist_manager.py", line 425, in <module>
    for stat in home_stats:
TypeError: 'NoneType' object is not iterable
```

I am also unable to use my own user for user selection. I get this error `playlist_manager.py: error: argument --user: invalid choice: `, I'm not sure if that's due to me changing my Plex username since it's still the old one in Tautulli. The user list doesn't show either of my usernames on the script

**Comment by blacktwin** [comment]
The first error is because you don't have values in the config.ini or you haven't added the URL/API/TOKEN to the script. You can do either or.

The second error, what are you putting for the IP? `http://` or `https://`?

The third, the examples should have helped prevent this. Basically if you are running it for the admin user then `--users` is not needed. If you just want to share out to users and not the admin then you'd use the `--users` arg. If you want to share out to users and create the playlist for the admin then `--users USERNAME` and `--self` are needed. `--self` being the arg that would create the playlist on the admin account.

**Comment by camjac251** [comment]
The config.ini has info in there set properly. Since the killstream script works. I'm using SSL on tautulli and I believe it's being forced.

**Comment by blacktwin** [comment]
The config.ini for the plexapi library, which this script uses, is separate from how the kill_stream.py works. See the main readme for finding the default path for the config.ini for the plexapi library.

**Comment by blacktwin** [comment]
@camjac251 resolved?
