### ISSUE TITLE
off_deck request

### ISSUE THREAD

**Issue by khaosx** [blacktwin/JBOPS#126]
Would it be possible to modify the off-deck script to work against "Continue Watching"? Here's my scenario:

* Playlist is "Time to go to sleep". Consists of about 6 shows, episodes are filtered by "last playback not in last 6 months"
* Playlist is shuffled, some episodes are watched. At some point, user wakes up and stops playback.
* Next morning, the show that was playing is now sitting in "Continue Watching" and "On Deck"
* Manually mark the episode in "Continue Watching". Show is no longer in on-Deck or Continue Watching.

If I run the off-deck script against the playlist "Time to go to sleep", then my playlist is destroyed for that show, as all episodes have now been marked as played today. A script that could be run daily that marked any episode contained in the playlist that is now in "Continue Watching" was played would solve this problem and allow for smart playlists to work as expected.

Thanks for the consideration!

**Comment by blacktwin** [comment]
Once you take something off deck by marking it as played/watched it will add the next episode in the series to On Deck. Thats why Off_deck goes through the entire series and marks them as played/watched. 

I'm not sure what would happened if you set your Smart Playlist to say watched limit of less than 2. As all episodes would have to have been marked as watched (watch count 1) to get off of On Deck. But it may stay in the Smart Playlist because the view count would still be less than 2. Does that make sense?

If you intend to use off_deck the value for truly unwatched content is now 1 view count. But thats also not explicitly true as you could still have content that was watched once and it would remain at 1 view count until watched. I think. 

Honestly this is hacky hack job of a way to clear On Deck. YMMV.

**Comment by khaosx** [comment]
Yep. Totally makes sense, except for one thing. Plex doesn't add back to on deck if everything in the series is already marked watched. I just tested it with my playlist, stopping in the middle of a show, and with a series not in the playlist, both stopping in the middle of a show and letting it play the entire episode. It didn't add it to on-deck. Not sure what's up with that, but here we are :)

Is there a way through the API to access the "Continue Watching" list?

**Comment by blacktwin** [comment]
Continue Watching is On Deck.

**Comment by khaosx** [comment]
OK, gotcha. Thanks for looking at this. Closing it up.

**Comment by blacktwin** [comment]
I'll double check your findings when I get a chance.

**Comment by blacktwin** [comment]
@khaosx Yeah you're right. Ok, so Continue Watching would be On Deck with a duration of the video played. Yeah I'm going to add this. May also want to add a check against the rest of the series that it is watched. If not watched then skip over.

**Comment by khaosx** [comment]
Right on! Thanks for looking into it - it will be a welcome addition to the toolkit.

**Comment by blacktwin** [comment]
Removing Continue Watching items is now added. Continue Watching items are defined as Show/On Deck/ViewOffset > 0. 

Please let me know how it works out for you.
