### ISSUE TITLE
Error when removing playlists with Playlist Manager

### ISSUE THREAD

**Issue by irodimus** [blacktwin/JBOPS#141]
Using commit https://github.com/blacktwin/JBOPS/commit/8651dc34dd10c526508c78cc90e57f2bbcf7981a , the error appears when deleting playlists:
```
plex-ht:Scripts administrator$ python playlist_manager.py --jbop popularMovies --libraries "Movies" --action remove --days 30 --top 25
Deleting the playlist(s)...
Traceback (most recent call last):
  File "playlist_manager.py", line 672, in <module>
    delete_playlist(data, opts.jbop)
  File "playlist_manager.py", line 517, in delete_playlist
    pop_movie = playlist_dict['pop_movie']
KeyError: 'pop_movie'
```
Tried to use the new random option and I got the error when attempting to update or remove the playlist. I tried updating or removing the popular movie playlists to make sure it was not the random option and I got the error too.

**Comment by blacktwin** [comment]
Looks like I need to still figure out deleting randoms.

`playlist_manager.py --action update --jbop random --limit 10 --libraries
 Movies "Movies Anime"`
Doesn't delete the previous random playlist.

**Comment by blacktwin** [comment]
@irodimus you want to give it it try?

**Comment by irodimus** [comment]
I've finally had a chance to run commit https://github.com/blacktwin/JBOPS/commit/0c815e459b503f0687e29bd606cb30daeca0a654 and tested adding, updating, and removing playlists. It all works great now!

I did try using the `--name` option and while it did create a named playlist, attempting to update or remove does not delete the playlist. Instead, updating the named playlist will just create a new named playlist and removing will not delete the named playlist. 

Other than that, this is great and I'm hoping to run the script daily so I have multiple playlists with different genres. It will go a long way to "suggest" something to watch.

**Comment by blacktwin** [comment]
Great. Thanks for the feedback. I often get tunnel vision and can't remember what all the different variations are to run to make sure everything is correct. I really appreciate it. I'll update again once I fix the `--name` issue. 

Thanks again!!

**Comment by blacktwin** [comment]
@irodimus So I think that this isn't going to be changed. The `--name` is for creating custom names for whatever playlist type you want. So using the `--name` alone we won't be able to know what the content/structure/type the playlist will have/be. So while `--jbops update` can update playlist types (popular/time/random) it wont be able to update a playlist by it's name, since the custom name could be anything.

The workaround is to delete the playlist by `--action remove --playlist "Custom Named PL"` then run with `--action add--name "Custom Named PL"`. Because the `--playlist` argument is already available and works with `--action remove` it would be redundant and more code to allow for `--action remove --name`.

`--name` for creating a custom name.
`--playlist` for selecting a playlist (typically for selecting playlists with a custom name).

So maybe `--name` should replace `--playlist` for selecting playlists?

**Comment by irodimus** [comment]
I see what you mean. Maybe `--name` can be removed and something like `--action add --playlists "Custom Name"` can be used to create the custom named playlist instead if not found? That way `--playlists` is handling stuff like that as it's already doing searches for the playlist given to remove.

**Comment by irodimus** [comment]
So I did a shell script with something like this:
```
python playlist_manager.py --action remove --playlists "Random"
python playlist_manager.py --jbop random --action add --name "Random" --libraries Movies --limit 50

python playlist_manager.py --action remove --playlists "Playlist 1"
python playlist_manager.py --jbop random --action add --name "Playlist 1" --libraries Movies --limit 50

etc...
```
I added multiple lines in this manner with a different playlist name and filter, like a channel. I then just set a job to run this script once a day and all the playlists are added and updated. The script attempts to remove the playlist first. If the playlist does not exist, it doesn't error and quits, but continues and creates the playlist, which is great. 

If I ever need to add a playlist or remove it, I just modify the script which is kinda cool. This effectively rotates those playlists everyday.

**Comment by blacktwin** [comment]
@irodimus I'm not done yet! :) . I've updated the code to have a separate title creation function and have the deletion function delete on the playlist name instead of the kind of playlist. These updates seem to resolve update with custom name or random playlist issue. 

So should help with shortening your shell script. Let me know.

**Comment by irodimus** [comment]
@blacktwin my bad, I had closed it as the initial issue was resolved and the workaround was working :)

I will test this when I get home.

**Comment by irodimus** [comment]
The 4c014cfc242ba699ea9592d937e467e12d0c5e05 commit does appear to allow for updating the playlist now but it seems it may have made the `--action remove` option not work. I tried:
```
plex-ht:Scripts administrator$ python playlist_manager.py --action remove --playlists "00 Random"
```
and it does not delete the playlist anymore. While `--action update` does work, it wont really make my script smaller as I may still need to add it first if I hadn't added the playlist before but the ability to update it if needed is good to have if I have to update manually.

**Comment by blacktwin** [comment]
You can run `--action update` for the initial creation. There is nothing to delete so it just creates it.

**Comment by irodimus** [comment]
Ah, just tried that and it worked as you mentioned.

**Comment by blacktwin** [comment]
@irodimus we good now?

**Comment by irodimus** [comment]
Everything is working great now! Thanks!
