### ISSUE TITLE
Add a few seconds before running: Limit User stream count, kill last stream

### ISSUE THREAD

**Issue by j0shii** [blacktwin/JBOPS#203]
Some people start playing, it indicates how they are playing 2 times, but it is not true. I don't know why, but in a few seconds or 1 minute it already marks as a single reproduction.
Is there any option for the script to run a few seconds later? Thank you.
Sorry for my bad English.

**Comment by blacktwin** [comment]
Not really, as Tautulli initiates the script because there is more than 1 stream. So adding a delay to the script would just delay the running of the script not the check for the amount of streams. Ultimately it's an issue with Plex. Plex is reporting 2 streams when really there is only 1 and so thats what Tautulli sees and reacts based on how you setup the agent. The script never checks how many streams a user has, it relies on Tautulli to know. Hope that helps.
