### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by oronso** [blacktwin/JBOPS#205]
Hi,

when I set a timeout on the tautulli script site  "The number of seconds to wait before killing the script. 0 to disable timeout." it seems, that does not work on some devices. They get kicked out immediately and therefore cant change to the correct settings (i.e. direct stream).

So, how can I give the user some time to adjust the transcoding (i.e. to direct stream) .. before their stream gets killed?

thanks a lot
Oronso

**Comment by blacktwin** [comment]
You can set the stream to transocde (any quality not original) or direct play (original quality) before starting play. 

The timeout you're referring to is for Tautulli to kill a script if it has been running for too long. It has nothing to do with how the kill_stream.py script kills a stream. If the timeout were to be set to 20 seconds and the script took longer than 20 seconds to complete then Tautulli would kill the script before it was able to complete.

**Comment by calmarc** [comment]
The settings 'direct play' (i.e. maximum and dissallow automatic adjustments - or whatever combination) do often not work (i.e. for Plex on android, or also for Plex on some TV's). I just checked it again .. unless were are all retards alltogether and do something wrong :) 
So on some devices, you have to change to direct play, after you start playing it - and therefore your nice script kills's the stream too eary, so people can't watch anything anymore.
Maybe any idea and hints to me, where to put some time.sleep() code or so .. with a check afterwards if it's still transcoding or not (it was initially, since tautulli triggered your script).. if not.. let it be.. else really kill it?
Maybe I can do that myself with some hints .. thank a lot!

**Comment by blacktwin** [comment]
@oronso @calmarc see #203 

@calmarc set the player to use Original Quality in the settings. For Android its found in  Settings > Quality. Disable Automatically adjust quality and set the streaming settings to Original Quality. Also set the Triggers:

Playback Start
Transcode Decision Change

**Comment by calmarc** [comment]
Thanks Blacktwin, but that does not work (even so it says 'maximum' here not 'original-quality' in those settings. Maximum is what I chose so. Actually, when playing the video, it even claims, it's original-quality, but it does transcode and says so on the streaming-details. I have to select transcode.. and then again original.. and then it's direct-strream. But that all takes some time into the playing of the video.
There are cases, where you can't even select the original-quality - when the device just does not support that according format - so also here it transcodes.. does not matter what settings are used.
So I still think, it's not possible to reliably force plex to use direct-stream - despite any setting. Plex, based on bugs or devices or whatever .. will transcode often enough .. but then we are the the initial problem.. that you can't play the video at all.. since it kills it immediately.
Again .. thank you very much for trying to help, but that approach does not seem to work here.
I would put a time.wait(30) into the begin of your script .. but I don't know how to check (after the 30 seconds) the status .. (transcode or direct stream). If direct-stream - exit the script. That's still the only solution that comes to my mind.
You don't happen to have some hints .. how to check about the transcode/direct-stream status there?
Either way, Thanks you :)

**Comment by blacktwin** [comment]
If it's a device and user that you don't care that if it transcodes then just add conditions to allow that device with the specific user to bypass the script entirely. 

Yes. The client will decide if it needs the source video to be transcoded. If a video needs to be transoded then the video format/codec is not natively supported by the client. Nothing you can do about that other than optimizing the video to a format/codec that is supported. 

Adding a wait or sleep will not change how the script works, only delay the killing of the stream, as I pointed out in the link I provided above. The script does have a function where it will kill long pauses, so the script will wait a time before check Tautulli's activity for the stream in question on whether it is still paused or not. You could start there.
