### ISSUE TITLE
Tautulli API cmd 'get_metadata' failed: None

### ISSUE THREAD

**Issue by enzobes** [blacktwin/JBOPS#209]
**Describe the bug**
`
Checking library: 'TV Shows' watch statuses...
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
Tautulli API cmd 'get_metadata' failed: None
The following items were added before 2019-12-12
Traceback (most recent call last):
  File "media_manager.py", line 423, in <module>
    added_at = datetime.datetime.utcfromtimestamp(float(item.added_at)).strftime("%Y-%m-%d")
TypeError: float() argument must be a string or a number
`

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/utility/media_manager.py

**To Reproduce**
`python media_manager.py --libraries "TV Shows"  --select unwatched --date "2019-12-12" --action show`

**Expected behavior**
Show unwatched Movies that were added before 2019-12-12

**Desktop (please complete the following information):**
 - OS: Debian 9 (Tautulli on Docker)
 - Python 2.7.13
**Additional context**
`
python media_manager.py --libraries "TV Shows"  --select watched --user User1 --action show
`
This command works but  same error as above if I replace `--select watched` but` --select unwatched`

**Comment by blacktwin** [comment]
I'm assuming your running the most recent version. There have been several commits in the last 3 days. Can you please confirm?

For the `get_metadata` errors this could be that the item has history but Tautulli is unable to find the item from Plex and look up the metadata. Has history but has been deleted. Or Tautulli just needs to `Refresh Media Info` for the library. Libraries > Select library > Media Info > `Refresh Media Info` > Wait.

The `TypeError` this is likely due to the item's metadata being empty. So `Refresh Media Info`.

Please `Refresh Media Info`, confirm the script version, and report back.

**Comment by enzobes** [comment]
Yes it works ! thank you, it come from the media info
