### ISSUE TITLE
playlist_manager.py Issue

### ISSUE THREAD

**Issue by ReenigneArcher** [blacktwin/JBOPS#224]
**Describe the bug**
1. This does not delete any aired today playlist.
    `python playlist_manager.py --jbop historyToday --action remove --self`

2. This does not create a playlist
    `python playlist_manager.py --jbop popularMovies --action add --self`

3. This will create a new playlist even if the same playlist already exists.
    `python playlist_manager.py --action share --allUsers --playlists "My Custom Playlist"`

https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

**To Reproduce**
1. Open command prompt
2. CD to script directory
3. Run codes above
4. Check playlists in Plex

**Expected behavior**
1. Delete existing aired today playlists
2. Create a playlist with popular movies
3. If playlist with same name already exists then delete it and recreate it.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win10 Pro (latest build)
 - Browser: Firefox
 - Python Version: 2.7

**Additional context**

**Comment by blacktwin** [comment]
1. Of the playlists you were expecting to have deleted, were titles changed?

2. Any error message? Can you provide your logs? What is the result of `python playlist_manager.py --jbop popularMovies --action show`? If nothing is showing up there would be no playlist to create.

3. That is the expected behavior of those arguments. Try this instead `python playlist_manager.py --action update --allUsers --playlists "My Custom Playlist"`

**Comment by ReenigneArcher** [comment]
1. Maybe some more info on this. I was just testing this all in the same day. I'm assuming it deletes only previous days. Will test more tomorrow... If I do update instead of add, will it rename the previous days playlist?

2. I was missing the libraries. Working now!

3. Okay I added a line to remove the playlist first, then a second one to share the playlist (update wouldn't share it if it didn't exist for that user yet). I think that is what the sync_playlist_to_users.py script does (try to delete, then add). I like this one better though because it has the --allUsers option.

P.S. If I use pythonw.exe instead of python.exe will there be any issues using any of these scripts?

**Comment by blacktwin** [comment]
1. The deletion for the `--jbop` types like your example will use the predefined name of `Aired Today {month}-{day} in History` to search. Since that name would be different on each run it wouldn't be able to delete the previous playlist as the code is now. `popularMovies` would work if the days used were the same, since the name of the Playlist wouldn't change.

2. oops, I didn't even think about that. Good catch!

3. You can use `update` for a first run. It'll try to delete but nothing should return as there wouldn't be a previous added Playlist matching the arguments. `update` is just `delete` then `add`.

P.S. Not sure why that would matter. Makes me think that you're using Tautulli to execute this script, which you shouldn't do. This script should be ran from cmd or terminal or via a scheduled task or cron. I don't see how it'd fit to be use from Tautulli.

**Comment by ReenigneArcher** [comment]
I am running from task scheduler. Set to run daily at midnight and immediately after a missed run. I do have some other scripts of yours I'm running in Tautulli. Just don't want the console window to pop up.

1. Okay, I think I'll modify the script so it just names it Aired Today in History (without the date) making it easier to search. Alternatively could a wildcard be used in the --playlist like "Aired Today*"? Also the example in the script says it deletes all previous aired today playlists.

2. The examples may need to be updated because libraries or alllibraries isn't in the popularMovies or popular Tv examples.

3. That did work for aired today and popular, but not the custom playlist I created on my admin account. Might try to create the playlist with logic using the search. How would it order the playlist? By aired date?

**Comment by blacktwin** [comment]
1. No wildcard support for the names. 

1 & 2. Need to update the examples then, thanks!

3. `update` should work with custom playlist as long as the custom name is the same. `Sort by original air date, oldest first`

So far it looks like updating the examples is the only issue here. Is that correct?

**Comment by ReenigneArcher** [comment]
Yes correct, and I will get you screenshots tonight of the playlist not being created if using update on custom playlists. Thanks!

**Comment by ReenigneArcher** [comment]
User Dave before running command.
![image](https://user-images.githubusercontent.com/42013603/84544717-d0d24080-accb-11ea-94f2-e5509abd6de1.png)

Admin user before running command.
![image](https://user-images.githubusercontent.com/42013603/84544778-f4958680-accb-11ea-913b-23cee5314f6e.png)

The command and output.
![image](https://user-images.githubusercontent.com/42013603/84544987-6241b280-accc-11ea-84b6-dc968c6adfba.png)

And User Dave does not have the playlist after the command.

**Comment by blacktwin** [comment]
Correct. That's not how update works. Add and update are used for building a playlist. You'd want to use `share` instead to share an existing playlist.

```
add - create new playlist for admin or users
    remove - remove playlist type or name from admin or users
    update - remove playlist type and create new playlist type for admin or users
    show - show contents of playlist type or admin or users current playlists
    share - share existing playlist by title from admin to users
```
