### ISSUE TITLE
[Req] Config file instead of modifying all the scripts

### ISSUE THREAD

**Issue by Mirabis** [blacktwin/JBOPS#37]
Hi,

is it possible to have it read a config file in the same or root directory of the repo? That way we can enter:

```
PLEXPY_APIKEY
PLEXPY_URL
```

and it will use it for all scripts in use

**Comment by blacktwin** [comment]
Yeah I've been thinking about that.

**Comment by mescon** [comment]
+1 on this one.
Whenever I do ``git pull`` I have to do a whole dance to get everything set up properly again.

**Comment by samip5** [comment]
@mescon I have already made the PR request for this, but time will tell if it will be merged. I hope so though.

**Comment by blacktwin** [comment]
The original intent of making this repo was to better organize my scripts that were gists. Gist doesn't notify the author when comments are made and searching to find the correct page the script was on was becoming a pain. The gists were all one off scripts that I thought people would just download and run. After moving to Github, I didn't really think people would grab/pull them all, just one or two. 

To setup the config it would need to be able to allow the scripts to work without the config file to allow people who just grab one or two to not have a problem. `if config: use config, else: use whats in the script`. 

Also once Tautulli is out of Beta then I'll be looking at all the scripts and either remove or update them to better fit Tautulli. So I don't think there is a point in updating all the scripts now if I'm just going to remove some (maybe most) of them.

**Comment by samip5** [comment]
@blacktwin  Ah, gotcha. :)

**Comment by mescon** [comment]
@blacktwin Much appreciated :-)
I think your little scripts have become essential to having peace of mind on my server!

**Comment by samip5** [comment]
@blacktwin Could you take a look at my PR (#42)?

**Comment by blacktwin** [comment]
@samip5 Check out the config-update branch. Specifically the [kill_stream.py](https://github.com/blacktwin/JBOPS/blob/config-update/killstream/kill_stream.py)

```python
TAUTULLI_URL = os.getenv('TAUTULLI_URL', TAUTULLI_FALLBACK_URL)
TAUTULLI_APIKEY = os.getenv('TAUTULLI_APIKEY', TAUTULLI_FALLBACK_APIKEY)
```
Tautulli now uses environmental variables. So with anything being executed by the script notification agent from Tautulli will allow you to pull the URL and APIKEY when the script is ran. With that I think I'm going to be using the `terminate_session` [API](https://github.com/Tautulli/Tautulli/blob/master/API.md#terminate_session) call from Tautulli instead of using the plexapi library to do it. 

For anything else that would be using the plexapi, the plexapi has it's own [configuration](http://python-plexapi.readthedocs.io/en/latest/configuration.html) file method. Load it once and done. Just import the config module and call what you want.

```python
from plexapi.server import CONFIG
PLEX_URL = CONFIG.data['auth'].get('server_baseurl')
PLEX_TOKEN = CONFIG.data['auth'].get('server_token')
```
The configuration file that the plexapi will use can hold anything so I think that would be the better way to go about it.
